name: Docker Image CI tags

on:
  push:
    tags:
      - v*.*.*


jobs:

  build:
    runs-on: ubuntu-latest


    steps:

    - name: Login to docker.io
      run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rmulyukov/nginxtest:${GITHUB_REF:10}
    - name: Push image to docker.io
      run: docker push rmulyukov/nginxtest:${GITHUB_REF:10}
    - name: Update tag in values.yaml
      run: |
          cd helm/myapp
          export TAG=${GITHUB_REF:10}
          echo $TAG
          sed -i 's/^    tag: .*/    tag: '$TAG'/g' values.yaml 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push origin HEAD:master --force
